services:
  local-ai:
    image: localai/localai:latest-aio-cpu # Use -aio-gpu if you have an NVIDIA GPU
    container_name: local-ai
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/readyz"]
      interval: 1m
      timeout: 10s
      retries: 3
    ports:
      - 8080:8080
    environment:
      - DEBUG=true
      - MODELS_PATH=/models
      - THREADS=4
    volumes:
      - ./models:/models
    restart: always
